services:
  db:
    image: postgres:17
    container_name: chatapp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - chatnet

  redis:
    image: redis:7
    container_name: chatapp_redis
    ports:
      - "6379:6379"
    networks:
      - chatnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - chatnet

volumes:
  db_data:

networks:
  chatnet:
    driver: bridge
