# fly.toml app configuration file generated for backend-lively-field-2207 on 2025-04-21T10:20:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-lively-field-2207'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = 256
  cpu_kind = 'shared'
  cpus = 1
